const foodItems = [
  {
    id: "pa-amb-oli",
    name: "Pa amb oli",
    category: "Vorspeisen",
    image: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Pan_tostado_mojado_con_aceite_de_oliva.jpg",
    fallbackImage: "",
    imageCredit: "Wikimedia Commons",
    description: "Brot mit Olivenöl, Tomate und meist Käse, Schinken, Wurst oder Fisch. Einfach, typisch und gut teilbar.",
    status: "offen",
    rating: 0,
    note: ""
  },
  {
    id: "empanadas",
    name: "Empanadas",
    category: "Vorspeisen",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkf9foSxAjvI9TadXWmvuE9fLtyc84irYyaR3pc6av2g&s=10",
    fallbackImage: "https://upload.wikimedia.org/wikipedia/commons/7/78/Tapa_de_empanadillitas.JPG",
    imageCredit: "Bildquelle prüfen",
    description: "Gefüllte Teigtaschen, warm oder kalt als Snack, Vorspeise oder für unterwegs.",
    status: "offen",
    rating: 0,
    note: ""
  },
  {
    id: "sopas-mallorquinas",
    name: "Sopas mallorquinas",
    category: "Vorspeisen",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbOhiO0DQKMb4BidQtN1R5vhH6-EsKaip6I1vH-qcHhw&s=10",
    fallbackImage: "https://upload.wikimedia.org/wikipedia/commons/8/84/SopesMallorquines.JPG",
    imageCredit: "Bildquelle prüfen",
    description: "Traditionelles Gericht mit Gemüse, Brot und Brühe. Eher herzhaft-rustikal als Suppe im klassischen Sinn.",
    status: "offen",
    rating: 0,
    note: ""
  },
  {
    id: "cordero-al-horno",
    name: "Cordero al Horno",
    category: "Hauptgang",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1_H0pkdz-fF21CM0caVu701eL8asIeruUGZOyD0koJg&s=10",
    fallbackImage: "https://upload.wikimedia.org/wikipedia/commons/3/31/Plato_de_lechazo%2C_Valladolid.jpg",
    imageCredit: "Bildquelle prüfen",
    description: "Lamm aus dem Ofen, oft langsam gegart und rustikal serviert.",
    status: "offen",
    rating: 0,
    note: ""
  },
  {
    id: "paella-ciega",
    name: "Paella Ciega",
    category: "Hauptgang",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSmnbLhO0aHxrxO5Z_VzA0Em4GorDphp_V8KsF7OW53Q&s=10",
    fallbackImage: "https://upload.wikimedia.org/wikipedia/commons/e/ed/01_Paella_Valenciana_original.jpg",
    imageCredit: "Bildquelle prüfen",
    description: "Paella ohne Schalen und Knochen, dadurch leichter zu essen. Gute Option für eine entspannte Runde.",
    status: "offen",
    rating: 0,
    note: ""
  },
  {
    id: "gato-de-almendra",
    name: "Gató de almendra",
    category: "Nachspeise",
    image: "https://upload.wikimedia.org/wikipedia/commons/b/b6/Tarta_de_Santiago-2010.jpg",
    fallbackImage: "",
    imageCredit: "Wikimedia Commons",
    description: "Mallorquinischer Mandelkuchen, häufig mit Eis oder Kaffee serviert.",
    status: "offen",
    rating: 0,
    note: ""
  },
  {
    id: "gelat-ametlla",
    name: "Gelat d’ametlla",
    category: "Nachspeise",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTjOUg2cscSecX8irl05A9Zmq_x7PNsWvDVAstPrU4GXQ&s=10",
    fallbackImage: "https://www.recetasmallorquinas.es/wp-content/uploads/2019/04/helado-de-almendra.jpg",
    imageCredit: "Bildquelle prüfen",
    description: "Mandeleis, passend zu Kuchen, Kaffee oder als einfacher Nachtisch an heißen Tagen.",
    status: "offen",
    rating: 0,
    note: ""
  },
  {
    id: "ensaimada",
    name: "Ensaimada",
    category: "Süßes",
    image: "https://cdn.tasteatlas.com/images/dishes/48612786ce2f4c00ab65c08f43a69f86.jpg",
    fallbackImage: "https://upload.wikimedia.org/wikipedia/commons/5/50/Ensaimada_3.jpg",
    imageCredit: "TasteAtlas",
    description: "Luftiges, schneckenförmiges Hefegebäck mit Puderzucker. Klassisch zum Kaffee oder Frühstück.",
    status: "offen",
    rating: 0,
    note: ""
  },
  {
    id: "sangria",
    name: "Sangria",
    category: "Getränke",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNcU0fxMAcES1lkNJzDk83cwduVT0PnDPnA1zt9SFg6A&s=10",
    fallbackImage: "https://upload.wikimedia.org/wikipedia/commons/b/b5/Red_Wine_Sangria_with_lemon%2C_lime%2C_apple%2C_and_orange_served_in_a_glass_-_Evan_Swigart.jpg",
    imageCredit: "Bildquelle prüfen",
    description: "Weinmischgetränk mit Früchten. Am besten gut gekühlt und eher dort probieren, wo es nicht nach Touristenfalle wirkt.",
    status: "offen",
    rating: 0,
    note: ""
  }
];
